        <div class="ms_upload_wrapper marger_top60 ">
            <div class="ms_upload_box previous">
                 <div class="">
                        <div class="ms_pro_img upload-image ">
                        </div>
                        <div class="ms_pro_form">
                            <div class="form-group">
                                    <form action="#" class="upa" enctype="multipart/form-data">
                                      <input class="avatar-input" onchange="readURL(this);" type="file" name="file" hidden>
                                      <div class="ms_upload_btn">
                                            <a href="#" class="ms_btn">Album cover</a>
                                        </div>
                                  </form>
                                </div>
                                  <div class="progress_area">
                                       
                                </div>
                        </div>
                            <div class="ms_pro_form">
                              <input type="hidden" name="img" value="" id="img_value">
                              <div class="form-group">
                                  <input type="text" name="albumname" id="an" placeholder="Album title *"  class="form-control">
                              </div>
                              <div class="form-group">
                                  <input type="text" name="artistname" id="arn" placeholder="Artist name"  class="form-control">
                              </div>
                                     <div class="form-group">
                                        <select name="genre" id="g" class="form-control">
                                        <option>Genre</option>
                                        <option value="1">Cyber Sonnet </option>
                                        <option value="2">Cloud Nine</option>
                                        <option value="3">Cyber Sonnet</option>
                                        <option value="4">Cloud Nine</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                      <div class="col-md-12">
                                        <textarea name="describtion" id="d" placeholder="desribtion"></textarea> 
                                      </div>
                                    </div>
                          
                            
                        </div>
                        <div class="pro-form-btn  marger_top15" style="float:right; margin-right:18px;">
                                        <div class="ms_upload_btn show_next">
                                            <a href="javascript:void();" class="ms_btn">Next</a>
                                        </div>
                        </div>

                  </div>
      </div>
            
                 <div class="next">
                <input type="hidden" name="" value="0" id="counter">
                 <div class="ms_upload_box">
                            <h2>Upload &amp; Share Your Music With The World</h2>
                            <div id="texthint"></div>
                            <img src="<?php echo $t['config']['site_url']?>images/svg/upload.svg" alt="">
                            <div class="ms_upload_btn">
        
                          
                            <form action="#" class="upm" enctype="multipart/form-data">
                                 <input class="file-input" type="file" name="file" hidden>
                                 <div class="ms_upload_btn ">
                                    <a href="#" class="ms_btn">Upload files</a>
                                </div>
                            </form>
                            </div>
                            <span> or </span>
                            <p>Drag And Drop Music Files</p>
                        </div>
                        <div class=" marger_top60">
                            <div class="ms_upload_box">
                                <div class="ms_heading hidden">
                                    <h1>Track Information</h1>
                                    </div>
                                <div id="files">
                                <section class="progress-area">
                                </section>
                                <section class="uploaded-area">                             
                                </section>

                                    <div class="pro-form-btn  text-center marger_top15">
                                        <div class="ms_upload_btn show_previous" style="float:left; margin-left:17px">
                                        <a href="#" class="ms_btn">Previous</a>
                                        </div>
                                        <div class="hidden ms_upload_btn upload_button">
                                            <a href="#" class="ms_btn">Upload Now</a>
                                        </div>
                            </div>
                                    </div>        
                                    
                                </div>
                                

                                
                        
                                <!-- <div class="ms_pro_form">
                                    <div class="form-group"> <label>Track Name *</label> <input type="text" placeholder="Dream Your Moments" class="form-control"></div><div class="form-group"><label>Artist’s Name *</label><input type="text" placeholder="Ava Cornish, Brian Hill" class="form-control"></div>
                                    <div class="form-group">
                                        <label>Select Album</label>
                                        <select class="form-control">
                                        <option>Cloud Nine</option>
                                        <option value="1">Cyber Sonnet </option>
                                        <option value="2">Cloud Nine</option>
                                        <option value="3">Cyber Sonnet</option>
                                        <option value="4">Cloud Nine</option>
                                    </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Select Privacy</label>
                                        <select class="form-control">
                                        <option>Public</option>
                                        <option value="1">Private</option>
                                        <option value="2">Public</option>
                                        <option value="3">Private</option>
                                        <option value="4">Public</option>
                                    </select>
                                    </div>
                                    <div class="pro-form-btn text-center marger_top15">
                                        <div class="ms_upload_btn">
                                            <a href="#" class="ms_btn">Upload Now</a>
                                            <a href="#" class="ms_btn">cancle</a>
                                        </div>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                 
                 
                 </div>
               
            <style>
            </style>

            <script type="text/html" id="files-template">
                            <div id="%%id%%">
                                <p style="font-size:14px" class="mb-2"><strong >%%filename%% </strong> Status:<span class="text-muted">Waiting</span></p><div class="w3-light-grey w3-round-xlarge"><div class="w3-round-xlarge"><div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div></div></div><div target1='hide' class="ms_pro_form hidden"><div   class="form-group"> <label>Track Name *</label><input type="text" id="" placeholder="Track name" class="form-control"> </div> <div class="form-group"><label>Artist’s Name *</label><input type="text" id="" placeholder="Artist's Name" class="form-control"></div></div><br></div>
                </script>
               
                <script>
                
                function readURL(input) {
                     
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $('.upload-image').html('<img src="' + e.target.result + '" class="img-fluid">');
                        };
                        reader.readAsDataURL(input.files[0]);
                    }
                }
                jQuery(document).ready(function(){
                    $('.next').hide();
            
                    $('.show_next').click(function(){
                         
                        $('.previous').slideUp('5000');
                        $('.next').slideDown('5000');
                    })
                    $('.show_previous').click(function(){
                     
                        $('.next').slideUp('5000');
                        $('.previous').slideDown('5000');
                    })
                })
                
                </script>
                   <!--Main js file Style-->
                   <script >
var ay = [];
function removeA(arr){
              var what, a = arguments, L = a.length, ax;
              while(L > 1 && arr.length){
                what = a[--L];
                while((ax=arr.indexOf(what)) !== -1){
                  arr.splice(ax, 1);
                }
              }
              return arr;
}
const upload_avatar = document.querySelector(".upa"),
avatar_input = document.querySelector(".avatar-input");
const form = document.querySelector(".upm"),
fileInput = document.querySelector(".file-input"),
progressArea = document.querySelector(".progress-area"),
uploadedArea = document.querySelector(".uploaded-area");
uploadedcover = document.querySelector(".progress_area");
// form click event
form.addEventListener("click", () =>{
  fileInput.click();
});
upload_avatar.addEventListener("click", () =>{
  avatar_input.click();
});
fileInput.onchange = ({target})=>{
  let file = target.files[0]; //getting file [0] this means if user has selected multiple files then get first one only
  if(file){
    let fileName = file.name; //getting file name
    
    if(fileName.length >= 12){ //if file name length is greater than 12 then split it and add ...
      let splitName = fileName.split('.');
      fileName = splitName[0].substring(0, 13) + "... ." + splitName[1];
     
    }
     c = document.getElementById('counter').value
     document.getElementById('counter').value = parseInt(c) + 1;
    uploadFile(fileName, file); //calling uploadFile with passing file name as an argument
  }
}
avatar_input.onchange = ({target})=>{
  let file = target.files[0]; //getting file [0] this means if user has selected multiple files then get first one only
   
  if(file){
    let fileName = file.name; //getting file name
    readURL(fileName);
    if(fileName.length >= 12){ //if file name length is greater than 12 then split it and add ...
      let splitName = fileName.split('.');
      fileName = splitName[0].substring(0, 13) + "... ." + splitName[1];
     
    }
    uploadcover(fileName, file); //calling uploadFile with passing file name as an argument
  }
}
// file upload function
function uploadcover(name, rf){
  let xhr = new XMLHttpRequest(); //creating new xhr object (AJAX)
  xhr.open("POST", "uploadcover.php", true); //sending post request to the specified URL
  
  xhr.upload.addEventListener("progress", ({loaded, total}) =>{ //file uploading progress event
    let fileLoaded = Math.floor((loaded / total) * 100);  //getting percentage of loaded file size
    let fileTotal = Math.floor(total / 1000); //gettting total file size in KB from bytes
    let fileSize;
    // if file size is less than 1024 then add only KB else convert this KB into MB
    (fileTotal < 1024) ? fileSize = fileTotal + " KB" : fileSize = (loaded / (1024*1024)).toFixed(2) + " MB";
    let progressHTML = ` <li class="ro">
                                          <div class="content">
                                          <span class="name">${name} • Uploading</span>
                                              <span class="percent">${fileLoaded}%</span>
                                            <div class="progress-bar">
                                              <div class="progress" style="width:${fileLoaded}%; height: 12px; border-radius:23px; background:;"></div>
                                            </div>
                                          </div>
                                      </li>`;
    // uploadedArea.innerHTML = ""; //uncomment this line if you don't want to show upload history
    // uploadedcover.classList.add("onprogress");
    uploadedcover.innerHTML = progressHTML;
    if(loaded == total){
      xhr.responseType = 'json';
       xhr.onreadystatechange = function() {
            if (xhr.readyState === 4 && xhr.status === 200) {
                // document.getElementById("texthint").innerHTML = xhr.responseXML;
                // console.log(xhr.responseXML);
                let responseObj = xhr.response;
                if(responseObj.status == 400){
                      console.log(responseObj);
                      v = responseObj.image_url;
                      document.getElementById('img_value').value = v;
                      //  let uploadedHTML = `<div class="ms_pro_form"><div class="form-group">  ${name}  • Uploaded    <span class="size">${fileSize}</span></label>`;
                       $('.upload-image').html('<img src="' + v + '" class="img-fluid">');
                       uploadedcover.innerHTML =''
                      // uploadedArea.insertAdjacentHTML("afterbegin", jk); //remove this line if you don't want to show upload history
                       
                }else{
                   
                  uploadedcover.innerHTML = "<b style='color:red'>"+responseObj.message+"</b>";
                }
            }
        };
      }
  });

  let data = new FormData(upload_avatar); //FormData is an object to easily send form data
  
  xhr.send(data); //sending form data
   
}

function uploadFile(name, rf){
  let xhr = new XMLHttpRequest(); //creating new xhr object (AJAX)
  xhr.open("POST", "upload.php", true); //sending post request to the specified URL
  
  xhr.upload.addEventListener("progress", ({loaded, total}) =>{ //file uploading progress event
    let fileLoaded = Math.floor((loaded / total) * 100);  //getting percentage of loaded file size
    let fileTotal = Math.floor(total / 1000); //gettting total file size in KB from bytes
    let fileSize;
    // if file size is less than 1024 then add only KB else convert this KB into MB
    (fileTotal < 1024) ? fileSize = fileTotal + " KB" : fileSize = (loaded / (1024*1024)).toFixed(2) + " MB";
    let progressHTML = `<li class="ro">
                          <i class="fas fa-file-alt"></i>
                          <div class="content">
                            <div class="details">
                              <span class="name">${name} • Uploading</span>
                              <span class="percent">${fileLoaded}%</span>
                            </div>
                            <div class="progress-bar">
                              <div class="progress" style="width: ${fileLoaded}%"></div>
                            </div>
                          </div>
                        </li>`;
    // uploadedArea.innerHTML = ""; //uncomment this line if you don't want to show upload history
    uploadedArea.classList.add("onprogress");
    progressArea.innerHTML = progressHTML;
    if(loaded == total){
      xhr.responseType = 'json';
       xhr.onreadystatechange = function() {
            if (xhr.readyState === 4 && xhr.status === 200) {
                // document.getElementById("texthint").innerHTML = xhr.responseXML;
                // console.log(xhr.responseXML);
                let responseObj = xhr.response;
                if(responseObj.status == 400){
                      console.log(responseObj);
                     
                      id = document.getElementById('counter').value;
                      ay.push(id);
                      v = responseObj.image_url;
                      progressArea.innerHTML = "";
                      //error_border
                      jk = '<div class="ms_pro_form " id="error_border'+id+'"><div class="form-group">  '+name+'  • Uploaded    <span class="size">'+fileSize+'</span> </label> <input id="title'+id+'" type="text" placeholder="Track Name" class="form-control"></div><div class="form-group"><input id="artistname'+id+'" type="text" placeholder="Artists name" class="form-control"><input type="hidden" id="path'+id+'" name="path" value="'+ v +'"></div>          <div class="form-group"><input type="text" name="tags" id="tag'+id+'" placeholder="Tag seperated by single space"  class="form-control"></div><div class="form-group"><select name="genre" id="g'+id+'" class="form-control"><option>Genre</option><option value="1">Cyber Sonnet </option><option value="2">Cloud Nine</option><option value="3">Cyber Sonnet</option><option value="4">Cloud Nine</option></select></div><p id="error_bordertext'+id+'" style="color:red"></p></div>';
                      let uploadedHTML = `<div class="ms_pro_form"><div class="form-group">  ${name}  • Uploaded    <span class="size">${fileSize}</span></label> <input id="title'+id+'" type="text" placeholder="Track Name" class="form-control"></div><div class="form-group"><input id="artist'+id+'" type="text" placeholder="Artists name" class="form-control"><input type="hidden" id="path'+id+'" name="path" value="'+ v +'"></div></div> `;
                      uploadedArea.classList.remove("onprogress");
                      // uploadedArea.innerHTML = uploadedHTML; //uncomment this line if you don't want to show upload history
                      uploadedArea.insertAdjacentHTML("afterbegin", jk); //remove this line if you don't want to show upload history
                      $('.upload_button').removeClass('hidden');
                      $('.ms_heading').removeClass('hidden');
                }else{
                  alert(responseObj.message);
                  progressArea.innerHTML = "";
                }
            }
        };
      }
  });

  let data = new FormData(form); //FormData is an object to easily send form data
  
  xhr.send(data); //sending form data
   
}
jQuery(document).ready(function(){
  AibumId = [];
  $('.upload_button').click(function(){
    var imgv = document.getElementById('img_value').value;
    var an = document.getElementById('an').value;
    var arn = document.getElementById('arn').value;
    var g = document.getElementById('g').value;
    var d = document.getElementById('d').value;
    if(imgv == '' || an == '' || arn == '' || g == '' || d == ''){
      alert('Please check Album details...')
    }else{
     if(AibumId.length == 0){
      $.ajax({
        url : Wo_Ajax_Requests_File() + '?f=uploadalbum',
        type : 'POST',
        dataType : 'Json',
        data : {imgv : imgv, an : an, arn : arn, g : g, d : d}
      }).done(function(data){
                             if (data['status'] == 400) {
                              //  alert(data['message']);
                               console.log('success');
                               AibumId = data['aid'];
                               for(i = 0; i < ay.length; i++){
                                  di = ay[i];
                                  title = document.getElementById('title'+di).value;
                                  artistname = document.getElementById('artistname'+di).value;
                                  music =  document.getElementById('path'+di).value;
                                  tag = document.getElementById('tag'+di).value;
                                  genre = document.getElementById('g'+di).value;
                                 
                                  if(title == '' || artistname == '' || music == '' || tag == '' || genre == ''){
                                    $('#error_border'+di).addClass('error_border');
                                    $('#error_bordertext'+id).text('All field are required');
                                  }else{
                                    insertMusic(imgv, artistname, title, music, AibumId, genre, d, tag, di);

                                  }
              
                                  
                                }
                            //window.location = data.url;
                            }  else if (data['message']) {
                            alert(data['message']);
                            }
      })
     }else{
                      for(i = 0; i < ay.length; i++){
                                  di = ay[i];
                                  title = document.getElementById('title'+di).value;
                                  artistname = document.getElementById('artistname'+di).value;
                                  music =  document.getElementById('path'+di).value;
                                  tag = document.getElementById('tag'+di).value;
                                  genre = document.getElementById('g'+di).value;
                                 
                                  if(title == '' || artistname == '' || music == '' || tag == '' || genre == ''){
                                    $('#error_border'+di).addClass('error_border');
                                    $('#error_bordertext'+id).text('All field are required');
                                  }else{
                                    insertMusic(imgv, artistname, title, music, AibumId, genre, d, tag, di);

                                  }
                                  
                                }
     }
    }
    // for(i = 0; i < ay.length; i++){
    //   d = ay[i];
    //   title = document.getElementById('title'+d).value;
    //   artistname = document.getElementById('artistname'+d).value;
    //   mdir =  document.getElementById('path'+d).value;
    //   console.log(d);
     
    // }
  })
})

// imgv, artistname, title, music, AibumId, genre, d, tag
function insertMusic(imgv, artistname, title, music, albumid, g, d, tag, id){
  $.ajax({
        url : Wo_Ajax_Requests_File() + '?f=uploadtrack',
        type : 'POST',
        dataType : 'Json',
        data : {imgv : imgv, artistname : artistname,  title : title, music : music, albumid : albumid,  g : g, d : d, tag : tag}
      }).done(function(data){
                             if (data['status'] == 400) {
                              $('#error_border'+id).hide();
                              removeA(ay, id);
                              if(ay.length == '0'){
                                    alert('Success: All track Added');
                                    window.location = data["url"];
                                  }
                              //window.location = data.url;
                            }  else if (data['message']) {
                              $('#error_border'+id).addClass('error_border');
                              $('#error_bordertext'+id).text('Your input can not be submited');
                              console.log(data['message'])
                            }
      });
}

  </script>
 

   
                <style>

section .ro{
  margin-bottom: 10px;
  /* background: #E9F0FF; */
  list-style: none;
  padding: 15px 20px;
  border-radius: 5px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
section .ro i{
  color: #6990F2;
  font-size: 30px;
}
section .details span{
  font-size: 14px;
}
.progress-area .ro .content{
  width: 100%;
  margin-left: 15px;
}
.progress-area .details{
  display: flex;
  align-items: center;
  margin-bottom: 7px;
  justify-content: space-between;
}
.progress-area .content .progress-bar{
  height: 6px;
  width: 100%;
  margin-bottom: 4px;
  background: #fff;
  border-radius: 30px;
}
.content .progress-bar .progress{
  height: 100%;
  width: 0%;
  background: #6990F2;
  border-radius: inherit;
}
.uploaded-area{
   
   
}
.uploaded-area.onprogress{
  max-height: 100px;
}
.uploaded-area::-webkit-scrollbar{
  width: 0px;
}
.uploaded-area .ro .content{
  display: flex;
  align-items: center;
}
.uploaded-area .ro .details{
  display: flex;
  margin-left: 15px;
  flex-direction: column;
}
.uploaded-area .ro .details .size{
  color: #404040;
  font-size: 11px;
}
.uploaded-area i.fa-check{
  font-size: 16px;
}
.error_border{
  border-radius : 20px;
  border-style : solid;
  border-color : red;
  border-width : 1px;
  margin-bottom : 12px;
}

                </style>
