
<style>
    .hiden{
    display: none !important;
    }
</style>
    <div class="timeline-page-wrapper">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters">
                            <div class="col-lg-6 order-2 order-lg-1">
                                <div class="timeline-bg-content bg-img" data-bg="assets/images/timeline/adda-timeline.jpg">
                                    <h3 class="timeline-bg-title">Let’s see what’s happening to you and your world. Welcome in Adda.</h3>
                                </div>
                            </div>
                            <div class="col-lg-6 order-1 order-lg-2 d-flex align-items-center justify-content-center">
                                <div class="signup-form-wrapper">
                                    <h1 class="create-acc text-center">Create An Account</h1>
                                    <div class="signup-inner text-center">
                                        <h3 class="title">Wellcome to Adda</h3>
                                        <!-- form -->
                                        <form class="signup-inner--form" id="register" method="post">
                                            <div class="row">
                                                <div class="errors"> <div class="inneralert"></div></div>
                                                <div class="loading_cont">
                                                    <div class="loading hidden"></div>
                                                </div>
                                                <div class="col-12">
                                                    <input class="single-field" name="firstname" type="text" id="firstname" placeholder="<?php echo  'First name';?>" autofocus />
                                                    <!-- <label for="username">Username</label> -->
                                                </div>
                                                <div class="col-12">
                                                    <input class="single-field" name="lastname" type="text" id="lastname" placeholder="<?php echo  'Last name';?>" autofocus />
                                                    <!-- <label for="username">Username</label> -->
                                                </div>
                                                <div class="col-12">
                                                        <input class="single-field" name="email" type="email" id="email_address" placeholder="<?php echo 'email Address' ?>" />
                                                        <!-- <label for="email_address"><?php //echo 'email Address' ?></label> -->
                                                </div>
                                                <?php if($t['config']['sms_or_email'] == 'sms') {?>
                                                    <div class="col-12">
                                                        <input class="single-field" name="phone_num" type="text" id="phone_num_ex" placeholder="<?php echo  'phone_num_ex';?>" />
                                                        <!-- <label for="phone_num_ex"><?php// echo  'phone_num_ex'?></label> -->
                                                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg> -->
                                                    </div>
                                                <?php } ?>
                                                <!-- <div class="col-md-6">
                                                    <input type="text" id="fn" name="firstname" class="single-field" placeholder="First Name">
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text" id="ln" name="lastname" class="single-field" placeholder="Last Name">
                                                </div> -->
                                                <div class="col-12">
                                                        <input class="single-field" name="password" type="password" id="password" placeholder="<?php echo  'password';?>" />
                                                        <!-- <label for="password"><?php echo 'password'?></label> -->
                                                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg> -->
                                                        <?php if ($t['config']['password_complexity_system'] == 1) { ?>
                                                            <ul class="helper-text">
                                                                <li class="length"><?php echo  'Least characters'; ?></li>
                                                                <li class="lowercase"><?php echo  'Contain lowercase'; ?></li>
                                                                <li class="uppercase"><?php echo  'Contain uppercase'; ?></li>
                                                                <li class="special"><?php echo  'Special number'; ?></li>
                                                            </ul>
                                                        <?php } ?>
                                                </div>
                                                <div class="col-12">
                                                    <input class="single-field" name="confirm_password" type="password" id="confirm_password" placeholder="<?php echo  'confirm password' ;?>" />
                                                    <!-- <label for="confirm_password"><?php echo  'confirm password'?></label> -->
                                                </div>
                                                <div class="col-md-6">
                                                    <select class="nice-select" name="gender" id="gender">
                                                        <option value="gender">Gender</option>
                                                        <option value="male">Male</option>
                                                        <option value="female">Female</option>
                                                    </select>
                                                </div>
                                                <div class="col-12"><p><input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)"> I have read & accepted the <a href="#">terms of use</a></p>
                                                    
                                                </div>
                                                <!-- <div class="col-md-6">
                                                    <select class="nice-select" name="sortby">
                                                        <option value="trending">Age</option>
                                                        <option value="sales">18+</option>
                                                        <option value="sales">18-</option>
                                                    </select>
                                                </div> -->
                                                <!-- <div class="col-12">
                                                    <select class="nice-select" name="sortby">
                                                        <option value="trending">Country</option>
                                                        <option value="sales">Bangladesh</option>
                                                        <option value="sales">Noakhali</option>
                                                        <option value="sales">Australia</option>
                                                        <option value="sales">China</option>
                                                    </select>
                                                </div> -->
                                                <div class="clear"></div>
                                                <div class="col-12">
                                                <!-- <button type="submit" class="btn btn-main" id="sign_submit" disabled> -->
                                                    <button type="submit" id="sign_submit" class="submit-btn" >Create Account</button>
                                                </div>
                                            </div>
                                           
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
 </div>

 