
<style>
    .hiden{
    display: none !important;
    }
</style>
    <div class="timeline-page-wrapper">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters">

                            <!-- forgot password html -->
                        <div class="loginf col-lg-12 order-1 order-lg-2 d-flex align-items-center justify-content-center">
                                <div class="signup-form-wrapper">
                                    
                                    <div class="signup-inner text-center">
                                        <h3 class="title">Enter email your Email address </h3>
                                        <!-- form -->
                                        <form id="fpass"  class="signup-inner--form" method="post">
                                            <div class="row">
                                                <div class="col-12">
                                                    <input class="single-field"  type="email" id="email_address" placeholder="Email Address" name="femail" />
                                                    <!-- <label for="username">Username</label> -->
                                                </div>
                                                <div class="clear"></div>
                                                <div class="col-12">
                                                <!-- <button type="submit" class="btn btn-main" id="sign_submit" disabled> -->
                                                    <button type="submit"  class="submit-btn" >Submit</button>
                                                    <p class="py-3 justify-content-center">Or</p>
                                                    <h6 class="justify-content-center" style="cursor:pointer;"><a style="text-decoration:none" href="<?php echo $t['config']['site_url'].'/welcome' ?>">Login </a></h6>
                                                    
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
             
                            
    
                        </div>
                    </div>
 </div>

 