
<style>
    .hiden{
    display: none !important;
    }
</style>
    <div class="timeline-page-wrapper">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters">

                            <!-- forgot password html -->
                        <div class="loginf col-lg-12 order-1 order-lg-2 d-flex align-items-center justify-content-center">
                                <div class="signup-form-wrapper">
                                    
                                    <div class="signup-inner text-center">
                                        <h3 class="title"> Create New Password</h3>
                                        <!-- form -->
                                        <form id="reset_password"  class="signup-inner--form" method="post">
                                            <div class="row">
                                                <div class="col-12">
                                                    <input class="single-field"  onkeyup='checkPass()' type="password" id="pass1" placeholder="Password" name="password" />
                                                    <!-- <label for="username">Username</label> -->
                                                </div>
                                                <div class="col-12">
                                                    <input class="single-field" id="pass2" onkeyup='checkPass()' onkeypress='checkPass()' onfocusout='checkPass()'  type="password" id="email_address" placeholder="Confirm Password" name="femail" />
                                                    <p style="margin-left:0px; color:red"  class=" mt-0 passinfo hiden">password not match</p>
                                                </div>
                                                <input type="hidden" name="email" vlaue="<?php  echo t_Secure($_GET['e'])?>">
                                                <input type="hidden" name="token" value="<?php echo t_Secure($_GET['t']) ?>">
                                                <div class="clear"></div>
                                                <div class="col-12">
                                                <!-- <button type="submit" class="btn btn-main" id="sign_submit" disabled> -->
                                                    <button type="submit"  class="submit-btn" >Submit</button>
                                                   
                                                    
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
 </div>

 