Hi there,
<br><br>
You have received an invitation request from your friend <a style="color:<?php echo $t['config']['btn_background_color'];?>" href="<?php echo $t['user']['url']?>"><?php echo $t['user']['name'];?></a> to join our social network community <a style="color:<?php echo $t['config']['btn_background_color'];?>" href="<?php echo $t['config']['site_url']. '/register?ref=' . $t['user']['username'] ?>"><?php echo $t['config']['siteName']?></a>.<br><br>
<a style="color:<?php echo $t['config']['btn_background_color'];?>" href="<?php echo $t['config']['site_url']. '/register?ref=' . $t['user']['username'] ?>">Let's contact & find your friends !</a>
<br><br>
<?php echo $t['config']['siteName']?> Team.
<br>
Best regards.