

<div class="ms_weekly_box">
                                <div class="weekly_left">
                                    <span class="w_top_no">
										<?php echo $i; ?>
									</span>
                                    <div class="w_top_song">
                                        <div class="w_tp_song_img">
                                            <img src="<?php echo $t['config']['site_url'].$data['cover']?>" alt="<?php echo $data['title'] ?>" class="img-fluid">
                                            <div class="ms_song_overlay">
                                            </div>
                                            <div class="ms_play_icon">
                                                <img src="<?php echo $t['config']['site_url']?>images/svg/play.svg" alt="">
                                            </div>
                                        </div>
                                        <div class="w_tp_song_name">
                                            <h3><a href="#"><?php echo $data['title'] ?></a></h3>
                                            <p><?php echo $data['artistname'] ?></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="weekly_right">
                                    <!-- <span class="w_song_time">5:10</span> -->
                                    <span class="ms_more_icon" data-other="1">
										<img src="<?php echo $t['config']['site_url']?>images/svg/more.svg" alt="">									
									</span>
                                </div>
                                <ul class="more_option">
           
                                    <li><a onclick="Downloadfile('<?php echo $data['music'] ?>')" href="#"><span class="opt_icon"><span class="icon icon_dwn"></span></span>Download Now</a></li>
                                    <li><a href="<?php echo $t['config']['site_url'] . 'track/ ' . base64_encode($data['title']) ?>"><span class="opt_icon"><span class="icon icon_view"></span></span>View</a></li>
                                    <li><a href="#"><span class="opt_icon"><span class="icon icon_share"></span></span>Share</a></li>
                                </ul>
                            </div> 