
<?php echo t_loadpage('sidebar/left'); ?>
<div class="col-lg-8 order-1 order-lg-2">
    <form class="form form-horizontal create-article-form" method="post" id="insert-blog" action="#">
                        <div class="setting-panel row">
                            <div class="form-group col-lg-12">
                                <label class="col-md-12" for="new-blog-title"><?php echo 'Title' ?></label>
                                <div class="col-md-12">
                                    <input id="blog_title" name="blog_title" type="text" class="form-control input-md" autofocus > 
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-md-12" for="new-blog-desc"><?php echo 'description'; ?></label>
                                <div class="col-md-12">
                                    <textarea name="blog_description" id="new-blog-desc" rows="3" type="text" class="form-control input-md"></textarea>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-md-12" for="new-blog-content"><?php echo 'Content'; ?></label>
                                <div class="col-md-12">
                                <textarea id="blog">Hello, World!</textarea>
                                </div>
                            </div>

                             
                            <div class="form-group col-lg-12">
                                <label class="col-md-12" for="new-blog-category"><?php echo 'Category'; ?></label>
                                <div class="col-md-12">
                                <select width="100%" name="blog_category" class="form-control" id="blog_category">
                                        <option value="0">
                                        <?php echo 'category';?>
                                        </option>
                                        
                                        <option value="1">
                                        <?php echo 'Education'; ?>
                                        </option>
                                        <option value="2">
                                        <?php echo 'Entertainment'; ?>
                                        </option>
                                        <option value="3">
                                        <?php echo 'Sport'; ?>
                                        </option>
                                        <option value="4">
                                        <?php echo 'Travel'; ?>
                                        </option>
                                        <option value="5">
                                        <?php echo 'Politics'; ?>
                                        </option>
                                        
                                    </select>     
                               </div>
                            </div>
                            <div class="col-12">
                            <section class="progress-area"></section>
                             <div id="drag-and-drop-zone" class="dm-uploader p-5">
                             <div class="main prv-img pointer" id="select-img" data-block="thumdrop-zone">
                                        <div class="thumbnail-rendderer">
                                            <div>
                                                <h4 class="bold"><?php echo 'Drop image here'; ?></h4>
                                                <div class="error-text-renderer"></div>
                                                <div>
                                                    <span><?php echo 'Or'; ?></span>
                                                    <p><?php echo 'Browse to upload'; ?></p>
                                                </div>
                                            </div> 
                                        </div>
                                    </div>
                              </div><!-- /uploader -->
                            </div>




                            
                            <input type="hidden" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
                        </div>
                        
                        <div class="setting-update-alert" id="blog-alert"></div>
                        <div class="form-group last-sett-btn modal-footer">
                            <div class="ball-pulse"><div></div><div></div><div></div></div>
                            <button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo 'publish'; ?></button>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo t_CreateSession();?>">
                        <input  name="image" type="hidden" id="upload" class="hidden">
    </form>
    <form action="#" class="f" enctype="multipart/form-data">
      <input class="file-input" type="file" name="file" accept="image/*" hidden >
      <i class="fas fa-cloud-upload-alt"></i>
      
    </form>
    <section class="progress-area"></section>
 </div>
       
 
    
<script>
const form = document.querySelector(".dm-uploader"),
f = document.querySelector(".f"),
fileInput = document.querySelector(".file-input"),
progressArea = document.querySelector(".progress-area"),
uploadedArea = document.querySelector(".uploaded-area");
// form click event
form.addEventListener("click", () =>{
  fileInput.click();
});

fileInput.onchange = ({target})=>{
  let file = target.files[0]; //getting file [0] this means if user has selected multiple files then get first one only
  if(file){
    let fileName = file.name; //getting file name
    if(fileName.length >= 12){ //if file name length is greater than 12 then split it and add ...
      let splitName = fileName.split('.');
      fileName = splitName[0].substring(0, 13) + "... ." + splitName[1];
     
    }
    uploadFile(fileName, file); //calling uploadFile with passing file name as an argument
  }
}

// file upload function
function uploadFile(name){
  let xhr = new XMLHttpRequest(); //creating new xhr object (AJAX)
  xhr.open("POST", "themes/uploadcover.php"); //sending post request to the specified URL
  xhr.upload.addEventListener("progress", ({loaded, total}) =>{ //file uploading progress event
    let fileLoaded = Math.floor((loaded / total) * 100);  //getting percentage of loaded file size
    let fileTotal = Math.floor(total / 1000); //gettting total file size in KB from bytes
    let fileSize;
    // if file size is less than 1024 then add only KB else convert this KB into MB
    (fileTotal < 1024) ? fileSize = fileTotal + " KB" : fileSize = (loaded / (1024*1024)).toFixed(2) + " MB";
    let progressHTML = `<li class="rrow">
                          <i class="fas fa-file-alt"></i>
                          <div class="content">
                            <div class="details">
                              <span class="name">${name} • Uploading</span>
                              <span class="percent">${fileLoaded}%</span>
                            </div>
                            <div class="progress-bar">
                              <div class="progress" style="width: ${fileLoaded}%"></div>
                            </div>
                          </div>
                        </li>`;
    uploadedArea.innerHTML = ""; //uncomment this line if you don't want to show upload history
    uploadedArea.classList.add("onprogress");
    progressArea.innerHTML = progressHTML;
    if(loaded == total){
      progressArea.innerHTML = "";
      let uploadedHTML = `<li class="row">
                            <div class="content upload">
                              <i class="fas fa-file-alt"></i>
                              <div class="details">
                                <span class="name">${name} • Uploaded</span>
                                <span class="size">${fileSize}</span>
                              </div>
                            </div>
                            <i class="fas fa-check"></i>
                          </li>`;
      uploadedArea.classList.remove("onprogress");
      // uploadedArea.innerHTML = uploadedHTML; //uncomment this line if you don't want to show upload history
      uploadedArea.insertAdjacentHTML("afterbegin", uploadedHTML); //remove this line if you don't want to show upload history
    }
  });
  let data = new FormData(f); //FormData is an object to easily send form data
  xhr.send(data); //sending form data

}


tinymce.init({
  selector: '#blog',
  height: 270,
  images_upload_credentials: true,
  paste_data_images: true,
  image_advtab: true,
  entity_encoding : "raw",
  images_upload_url: Wo_Ajax_Requests_File() + '?f=upload-blog-image',
  toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
  toolbar2: "print preview media | forecolor backcolor emoticons",
  plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    file_picker_callback: function(callback, value, meta) {
      if (meta.filetype == 'image') {
        $('#upload').trigger('click');
        $('#upload').on('change', function() {
          var file = this.files[0];
          var reader = new FileReader();
          reader.onload = function(e) {
            callback(e.target.result, {
              alt: ''
            });
          };
          reader.readAsDataURL(file);
        });
      }
    },
});
</script> 
<style>
  .progress-area .rrow .content{
  width: 100%;
  margin-left: 15px;
}
.progress-area .details{
  display: flex;
  align-items: center;
  margin-bottom: 7px;
  justify-content: space-between;
}
.progress-area .content .progress-bar{
  height: 6px;
  width: 100%;
  margin-bottom: 4px;
  background: #fff;
  border-radius: 30px;
}
.content .progress-bar .progress{
  height: 100%;
  width: 0%;
  background: #6990F2;
  border-radius: inherit;
}
  .dm-uploader {
	border: 0.25rem dashed #A5A5C7;
	text-align: center;
} 
/* #files {
    overflow-y: scroll !important;
    min-height: 920px;
} */
/* @media (min-width: 768px) {
	#files {
		min-height: 0;
	}
} */
/* #debug {
	overflow-y: scroll !important;
	height: 180px;	
} */

.dm-uploader {
	border: 0.25rem dashed #A5A5C7;
	text-align: center;
}
.dm-uploader.active {
	border-color: red;

	border-style: solid;
}
</style> 