<!DOCTYPE html>

<html lang="en">
 

<head>
    <title></title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="description" content="Music">
    <meta name="keywords" content="">
    <meta name="author" content="kamleshyadav">
    <meta name="MobileOptimized" content="320">
    <!--Start Style -->
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>css/w3.css">    
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>css/fonts.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>js/plugins/swiper/css/swiper.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>js/plugins/nice_select/nice-select.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>js/plugins/player/volume.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>js/plugins/scroll/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $t['config']['site_url']?>css/style.css">
    <!-- Favicon Link -->
    <link rel="shortcut icon" type="image/png" href="<?php echo $t['config']['site_url']?>images/favicon.png">
  <?php if($t['page'] == 'upload'){?>
  <link rel="stylesheet" href="<?php echo $t['config']['site_url']?>libraries\uploader-master\dist\css\jquery.dm-uploader.min.css">
  <link rel="stylesheet" href="<?php echo $t['config']['site_url']?>libraries\uploader-master\demo\styles.css">
  <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/jquery.js"></script>
  <?php } ?>
</head>

<body>
<script>
          function Wo_Ajax_Requests_File(){
            return "<?php echo $t['config']['site_url'].'/requests.php';?>";
         }
    </script>
	<!----Loader Start---->
	<!-- <div class="ms_loader">
		<div class="wrap">
		  <img src="images/loader.gif" alt="">
		</div>
	</div> -->
    <!----Main Wrapper Start---->
    <div class="ms_main_wrapper">
        <!---Side Menu Start--->
       <?php echo  t_loadpage('header/content') ?>
        <!---Main Content Start--->
        <div class="ms_content_wrapper padder_top80">
            <!---Header--->

            <?php
              if( $t['loggedin'] === true){
             echo t_loadpage('header/loggedinheader');
              }else{
                echo t_loadpage('header/header');
              }
              ?>
            <!---Banner--->
            <?php  echo $t['content']; ?>
            <!----Main div close---->
        </div>
        <!----Footer Start---->
        <?php echo t_loadpage('footer/content') ?>
        <!----Audio Player Section---->
       <?php echo t_loadpage('player/content') ?>
    </div>
    <!----Register Modal Start---->
    <!-- Modal -->
   <?php echo t_loadpage('register/content')  ?>
     
	<!----Queue Clear Model ---->
	<?php echo t_loadpage('player/quene') ?>		
    <!--Main js file Style-->
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/jqueryform.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/swiper/js/swiper.min.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/player/jplayer.playlist.min.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/player/jquery.jplayer.min.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/player/audio-player.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/player/volume.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/nice_select/jquery.nice-select.min.js"></script>
	<script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/plugins/scroll/jquery.mCustomScrollbar.js"></script>
    <script type="text/javascript" src="<?php echo $t['config']['site_url']?>js/custom.js"></script>
    
</body>
<script>
  // console.log("<?php //echo $t['user']['user_id'] ?>");
var working = false;
$(function() {
  
  document.getElementById("sign_submit").disabled = true;
  var $this = $('#register');
  var $state = $this.find('.errors');
  var $inneralert = $this.find('.inneralert');
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=register',
    beforeSend: function() {
    <?php if ($t['config']['password_complexity_system'] == 1) { ?>
    	if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
    		working = true;
			$this.find('button').attr("disabled", true);
			$this.find('button').text('Please wait...');
    	}
    	else{
        $state.addClass('error-message');
    		$inneralert.html("<?php echo 'Your password must contain <br> lowercase, uppercase, number and special character'; ?>");
    		return false;
    	}
        <?php } else{ ?>
        	working = true;
			$this.find('button').attr("disabled", true);
			 
        <?php } ?>
    },
    success: function(data) {
      if (data.status == 200) {
     $state.removeClass('error-message');
	   $state.addClass('success-message');
     $inneralert.html(data.message);
     $this.find('button').text('Welcome');
     console.log('success');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else if (data.status == 300) {
        window.location.href = data.location;
      } else {
        $this.find('button').attr("disabled", false);
	     $this.find('button').text('Create Account');
        $state.removeClass('success-message');
        $state.addClass('error-message');
        $inneralert.html('oyin is a beauty');
        console.log(data);
        console.log('failed');
      }
      working = false;
    }
  });
});

function activateButton(element) {
	if(element.checked) {
		document.getElementById("sign_submit").disabled = false;
	}
	else  {
		document.getElementById("sign_submit").disabled = true;
	}
};

 
//login
$(function() {
  $this = $('#login');
  $('#login').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=login',
    beforeSend: function() {
		working = true;
		$this.find('button').attr("disabled", true);
    $('.error_message').removeClass('error');
    $('.error_message').removeClass('success');
    $('.inerror').text('Please wait...')
    $('#error_modal').modal('show');
	//	$this.find('.loading').removeClass('hidden');
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
         
        $('.error_message').removeClass('error');
        $('.error_message').addClass('success');
        $('.inerror').html('Welcome Back')
      //	$state.addClass('success-alert');
        console.log('welcome back');
        //$state.html('<?php //echo $wo['lang']['welcome_back'] ?>');
	//	$this.find('.loading').addClass('hidden');
        setTimeout(function () {
        	window.location.href = data.location;
        }, 5000);
      } else {
        var errors = data.errors.join("<br>");
        $('.error_message').removeClass('sucess');
        $('.error_message').addClass('error');
        $('.inerror').html(errors)
        $this.find('button').attr("disabled", false);
      // $this.find('.loading').addClass('hidden');
        // $state.html(errors);
        console.log('errors');
        console.log(data);
      } 
      working = false;
    }
  });
});
</script>

<style type="text/css">
.hidden{
  display : none;
}
.show{
  display : block !important;
}
	 .helper-text {
	    display: none;
	    margin-top: 6px;
      margin-left: 0px !important;
	    font-size: 12px;
	    line-height: 22px;
	    color: #808080;
	  }
	  li.valid {
      color: #1fd34a;
    }
    .error-message,.success-message{font-size:15px;color:#fff;border-radius:5px;width:100%;padding:10px}
    .success-message{background-color:#89ba73}
    .error-message{background-color:#af5b5b}
    .error, .success {padding: 4px;font-size: 13px;margin-bottom: 10px;border: 1px solid;border-radius: 5px;}
    .error i, .success i, .error:empty, .success:empty {display: none;}
    .error {color: red}
    .success {color: green}
     /*Password Check*/
    .helper-text {display: none;margin-top: 6px;font-size: 12px;line-height: 18px;}
    .helper-text li.valid {color: #1aac20;}
</style>

</html>