<div class="ms-banner">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="ms_banner_img">
                                <img src="<?php echo $t['config']['site_url']?>images/banner.png" alt="" class="img-fluid">
                            </div>
                            <div class="ms_banner_text">
                                <h1>This Month’s</h1>
                                <h1 class="ms_color">Record Breaking Albums !</h1>
                                <p>Dream your moments, Until I Met You, Gimme Some Courage, Dark Alley, One More Of A Stranger, Endless<br> Things, The Heartbeat Stops, Walking Promises, Desired Games and many more...</p>
                                <div class="ms_banner_btn">
                                    <a href="#" class="ms_btn">Listen Now</a>
                                    <a href="#" class="ms_btn">Add To Queue</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!---Recently Played Music--->
            <?php echo t_loadpage('home/recent') ?>
            <!---Weekly Top 15--->
            <?php echo t_loadpage('home/weekly') ?>
            <!---Featured Artists Music--->
            <?php echo t_loadpage('home/featured') ?>
			<!----Add Section Start---->
			<?php echo t_loadpage('home/ads') ?>
            <!----New Releases Section Start---->
            <?php echo t_loadpage('home/release') ?>
            <!----Featured Albumn Section Start---->
            <?php echo t_loadpage('home/album') ?>
            <!----Top Genres Section Start---->
            <?php echo t_loadpage('home/topgenre') ?>
			<!----Add Section Start---->
            <?php echo t_loadpage('home/ads') ?>
            <!----Live Radio Section Start---->
           <?php echo t_loadpage('home/liveradio') ?>