<div class="timeline-header">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters align-items-center">
                            <div class="col-lg-6">
                                <div class="timeline-logo-area d-flex align-items-center">
                                    <div class="timeline-logo">
                                        <a href="index.html">
                                            <img src="assets/images/logo/logo.png" alt="timeline logo">
                                        </a>
                                    </div>
                                    <div class="timeline-tagline">
                                        <h6 class="tagline">It’s helps you to connect and share with the people in your life</h6>
                                    </div>
                                </div>
                            </div>
                            <form   id="login"  method="post">
                                <div class="col-lg-6">
                                    <div class="login-area">
                                        <div class="row align-items-center">
                                    
                                        <div class="col-12 col-sm">
                                                <input type="text" placeholder="Email or Userame" name="username" class="single-field">
                                            </div>
                                            <div class="col-12 col-sm">
                                                <input name="password" type="password" placeholder="Password" class="single-field">
                                            </div>
                                            <div class="col-12 col-sm-auto">
                                                <button type="submit" class="login-btn">Login</button>
                                            </div>
                                        
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>