<div class="ms_register_popup">
        <div id="myModal" class="modal  centered-modal" role="dialog">
            <div class="modal-dialog register_dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal">
						<i class="fa_icon form_close"></i>
					</button>
                    <div class="modal-body">
                        <div class="ms_register_img">
                            <img src="<?php echo $t['config']['site_url']?>images/register_img.png" alt="" class="img-fluid" />
                        </div>
                        <div class="ms_register_form">
                            <h2>Register / Sign Up</h2>
                            <div class="errors">
                                <div class="inneralert"></div>
                            </div>
                            <form id="register" method="post">
                                <div class="form-group">
                                        <input name="firstname" type="text" placeholder="Enter Your Name" class="form-control">
                                        <span class="form_icon">
                                    <i class="fa_icon form-user" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class="form-group">
                                            <input type="text" name="email" placeholder="Enter Your Email" class="form-control">
                                            <span class="form_icon">
                                        <i class="fa_icon form-envelope" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class="form-group">
                                            <input name="password" type="password" placeholder="Enter Password" class="form-control">
                                            <span class="form_icon">
                                    <i class="fa_icon form-lock" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class="form-group">
                                            <input name="confirm_password" type="password" placeholder="Confirm Password" class="form-control">
                                            <span class="form_icon">
                                    <i class=" fa_icon form-lock" aria-hidden="true"></i>
                                    </span>
                                </div>
                                    <div class="remember_checkbox">
                                                <label>I have read & accepted the <a href="#">terms of use</a>
                                            <input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                <input type="submit" id="sign_submit" value="Register" class="d">
                            <p>Already Have An Account? <a href="#myModal1" data-toggle="modal" class="ms_modal hideCurrentModel">login here</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!----Login Popup Start---->
        <div id="myModal1" class="modal  centered-modal" role="dialog">
            <div class="modal-dialog login_dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal">
						<i class="fa_icon form_close"></i>
					</button>
                    <div class="modal-body">
                        <div class="ms_register_img">
                            <img src="<?php echo $t['config']['site_url']?>images/register_img.png" alt="" class="img-fluid" />
                        </div>
                        <div class="ms_register_form">
                            <h2>login / Sign in</h2>
                            <form id="login"  method="post">
                                <div class="form-group">
                                    <input name="username" type="text" placeholder="Enter Your Email" class="form-control">
                                    <span class="form_icon">
                                        <i class="fa_icon form-envelope" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class="form-group">
                                        <input name="password" type="password" placeholder="Enter Password" class="form-control">
                                        <span class="form_icon">
                                        <i class="fa_icon form-lock" aria-hidden="true"></i>
                                        </span>
                                </div>
                                <div class="remember_checkbox">
                                            <label>Keep me signed in
                                            <input type="checkbox">
                                            <span class="checkmark"></span>
                                            </label>
                                </div>
                                <input type="submit" value="Login" class="d  btn-primary btn login-btn">
                               
                            </form>
                            <div class="popup_forgot">
                                <a href="#">Forgot Password ?</a>
                            </div>
                            <p>Don't Have An Account? <a href="#myModal" data-toggle="modal" class="ms_modal1 hideCurrentModel">register here</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>